### ISSUE TITLE
thank you! and also...

### ISSUE THREAD

**Issue by eksynn** [blankaex/fku-scripts#1]
thank you for picking up mieruko! ♡

just wondering if you guys wouldn't be interested in picking up this one as well
https://urasunday.com/title/1218

it's similar to mieruko but no translations so far (as far as i can see anyway)
what do you guys think?

also, do you guys have a discord server?

**Comment by eksynn** [comment]
<code>actually.... now that i took a more careful look at the raws, it may actually not be in your interests, as it's very... ecchi lol
(it was suggested by someone in a discord server when i asked about manga similar to mieruko)

but do you guys have a discord server?

**Comment by blankaex** [comment]
I admit I wasn't expecting anyone to raise issues on this repo. I usually don't respond to comments but you've figured out how to get my attention. 🤔 

We don't have any plans to pick up new series any time soon. We're not on Discord but you can find us on IRC if you want to chat with us. Link is on our group page on MD.
