### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by SquirrelKiev** [blankaex/fku-scripts#6]
Hello,
Apologies for reaching out like this! Attempted over the last couple days in IRC but didn't seem like its checked anymore. Just wondered if Mieruko-chan chapter 60 was still being worked on? The only translation up on Mangadex right now is a machine translated one and to say the least, it's not ideal
Either way though, thanks for working on Mieruko-chan for the last, what, 6 years? your work has been consistently very high quality and very appreciated!

**Comment by blankaex** [comment]
Hey, yeah chapter 60 is still in the works. It's fully translated and edited, you can see the script here: https://github.com/blankaex/fku-scripts/blob/master/Mieruko-chan/scripts/60.ass
We're currently waiting on availability for typesetting, but the project is still ongoing.
